import MetaSearchAgent from '@/lib/search/metaSearchAgent';
import prompts from '../prompts';

export const searchHandlers: Record<string, MetaSearchAgent> = {
  webSearch: new MetaSearchAgent({
    activeEngines: [],
    queryGeneratorPrompt: prompts.webSearchRetrieverPrompt,
    responsePrompt: prompts.webSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    maxSources: 10,
  }),
  academicSearch: new MetaSearchAgent({
    activeEngines: ['arxiv', 'google scholar', 'pubmed'],
    queryGeneratorPrompt: prompts.academicSearchRetrieverPrompt,
    responsePrompt: prompts.academicSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: true,
    maxSources: 12,
  }),
  news: new MetaSearchAgent({
    activeEngines: ['google news', 'bing news', 'yahoo news', 'brave.news', 'google', 'bing', 'yahoo', 'duckduckgo', 'qwant news'],
    queryGeneratorPrompt: prompts.newsRetrieverPrompt,
    responsePrompt: prompts.newsResponsePrompt,
    rerank: true,
    rerankThreshold: 0.2,
    searchWeb: true,
    maxSources: 12,
  }),
  macroEconomy: new MetaSearchAgent({
    activeEngines: ['google', 'bing', 'brave', 'duckduckgo', 'google news'],
    queryGeneratorPrompt: prompts.macroEconomyRetrieverPrompt,
    responsePrompt: prompts.macroEconomyResponsePrompt,
    rerank: true,
    rerankThreshold: 0.2,
    searchWeb: true,
    maxSources: 10,
  }),
  fundamentals: new MetaSearchAgent({
    activeEngines: ['google', 'bing', 'brave', 'yahoo', 'duckduckgo'],
    queryGeneratorPrompt: prompts.fundamentalsRetrieverPrompt,
    responsePrompt: prompts.fundamentalsResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    maxSources: 10,
  }),
  social: new MetaSearchAgent({
    activeEngines: ['reddit', 'youtube', 'google', 'bing', 'brave', 'duckduckgo', 'qwant news'],
    queryGeneratorPrompt: prompts.socialRetrieverPrompt,
    responsePrompt: prompts.socialResponsePrompt,
    rerank: true,
    rerankThreshold: 0.2,
    searchWeb: true,
    maxSources: 12,
  }),
  writingAssistant: new MetaSearchAgent({
    activeEngines: [],
    queryGeneratorPrompt: '',
    responsePrompt: prompts.writingAssistantPrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: false,
    summarizer: false, // Explicitly disable for writing assistant since it doesn't search web
    maxSources: 5,
  }),
  wolframAlphaSearch: new MetaSearchAgent({
    activeEngines: ['wolframalpha'],
    queryGeneratorPrompt: prompts.wolframAlphaSearchRetrieverPrompt,
    responsePrompt: prompts.wolframAlphaSearchResponsePrompt,
    rerank: false,
    rerankThreshold: 0,
    searchWeb: true,
    maxSources: 10,
  }),
  youtubeSearch: new MetaSearchAgent({
    activeEngines: ['youtube'],
    queryGeneratorPrompt: prompts.youtubeSearchRetrieverPrompt,
    responsePrompt: prompts.youtubeSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    maxSources: 10,
  }),
  redditSearch: new MetaSearchAgent({
    activeEngines: ['reddit'],
    queryGeneratorPrompt: prompts.redditSearchRetrieverPrompt,
    responsePrompt: prompts.redditSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    maxSources: 10,
  }),
};
